package game;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author BOOL&QUIZ
 */
public class gui_chara extends javax.swing.JFrame {
    public static int karakter=1;
    public static String username;

    /**
     * Creates new form gui_chara
     */
    public gui_chara() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        nama = new javax.swing.JTextField();
        prev = new javax.swing.JButton();
        next = new javax.swing.JButton();
        chara = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        siap = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bool & Quiz");

        jPanel2.setLayout(null);

        nama.setFont(new java.awt.Font("Lithos Pro Regular", 1, 14)); // NOI18N
        nama.setText("Masukkan nama");
        jPanel2.add(nama);
        nama.setBounds(150, 380, 150, 30);

        prev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/back hehe.png"))); // NOI18N
        prev.setBorder(null);
        prev.setBorderPainted(false);
        prev.setContentAreaFilled(false);
        prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevActionPerformed(evt);
            }
        });
        jPanel2.add(prev);
        prev.setBounds(60, 260, 50, 50);

        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/back kanan hehe.png"))); // NOI18N
        next.setBorder(null);
        next.setBorderPainted(false);
        next.setContentAreaFilled(false);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel2.add(next);
        next.setBounds(340, 260, 50, 50);

        chara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1.gif"))); // NOI18N
        jPanel2.add(chara);
        chara.setBounds(130, 180, 200, 200);

        jLabel3.setFont(new java.awt.Font("Lithos Pro Regular", 1, 36)); // NOI18N
        jLabel3.setText("PILIH KARAKTER");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 50, 350, 50);

        siap.setBackground(new java.awt.Color(255, 255, 255));
        siap.setFont(new java.awt.Font("Lithos Pro Regular", 1, 20)); // NOI18N
        siap.setText("SIAP");
        siap.setBorder(null);
        siap.setBorderPainted(false);
        siap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siapActionPerformed(evt);
            }
        });
        jPanel2.add(siap);
        siap.setBounds(180, 420, 93, 29);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/back hehe.png"))); // NOI18N
        back.setBorder(null);
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back);
        back.setBounds(10, 540, 50, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/at52.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 450, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        //Baru
        karakter=2;
        chara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/2.gif")));
    }//GEN-LAST:event_nextActionPerformed

    private void prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevActionPerformed
        // TODO add your handling code here:
        //Baru
        karakter=1;
        chara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1.gif")));
        
    }//GEN-LAST:event_prevActionPerformed

    private void siapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siapActionPerformed
        // TODO add your handling code here:
        username=nama.getText();
        Person y = new Person(username, karakter );
        SystemGame x = new SystemGame(true, username);
        InGameFrame game = new InGameFrame();
        this.setVisible(false);
        game.setVisible(true);
    }//GEN-LAST:event_siapActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        MenuUtama x = new MenuUtama();
        this.setVisible(false);
        x.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui_chara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui_chara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui_chara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui_chara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui_chara().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel chara;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nama;
    private javax.swing.JButton next;
    private javax.swing.JButton prev;
    private javax.swing.JButton siap;
    // End of variables declaration//GEN-END:variables
}
