/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import java.sql.Connection;

/**
 *
 * @author BOOL&QUIZ
 */
public class InGameFrame extends javax.swing.JFrame implements Abstract {

    int tidak, detik = 5, loop = 1, jawab, id;
    String quest, sql, info;

    /**
     * Creates new form Panel
     */
    public InGameFrame() {
        initComponents();
        Thread xxx = new Thread(gimsistem);
        xxx.start();
        char2.setVisible(false);
        char1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogpause = new javax.swing.JDialog();
        pauselabel = new javax.swing.JLabel();
        resume = new javax.swing.JButton();
        mainmenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        dialogkonfirmasi = new javax.swing.JDialog();
        setujubutton = new javax.swing.JButton();
        tidaksetujubutton = new javax.swing.JButton();
        konfirmasi = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbenar = new javax.swing.JDialog();
        labelbenar = new javax.swing.JLabel();
        jsalah = new javax.swing.JDialog();
        labelsalah = new javax.swing.JLabel();
        gameover = new javax.swing.JDialog();
        setujubutton1 = new javax.swing.JButton();
        tidaksetujubutton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namascore = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        panelSoal = new javax.swing.JScrollPane();
        soal = new javax.swing.JTextArea();
        score = new javax.swing.JLabel();
        pause = new javax.swing.JButton();
        garis3 = new javax.swing.JPanel();
        buttonbenar = new javax.swing.JButton();
        salahbutton = new javax.swing.JButton();
        waktu = new javax.swing.JLabel();
        char2 = new javax.swing.JLabel();
        char1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        dialogpause.setBackground(new java.awt.Color(153, 153, 153));
        dialogpause.setUndecorated(true);
        dialogpause.getContentPane().setLayout(null);

        pauselabel.setFont(new java.awt.Font("Lithos Pro Regular", 1, 36)); // NOI18N
        pauselabel.setForeground(new java.awt.Color(255, 255, 255));
        pauselabel.setText("PAUSE");
        dialogpause.getContentPane().add(pauselabel);
        pauselabel.setBounds(129, 88, 130, 37);

        resume.setBackground(new java.awt.Color(255, 255, 255));
        resume.setFont(new java.awt.Font("Lithos Pro Regular", 1, 20)); // NOI18N
        resume.setText("RESUME");
        resume.setMaximumSize(new java.awt.Dimension(95, 25));
        resume.setMinimumSize(new java.awt.Dimension(95, 25));
        resume.setPreferredSize(new java.awt.Dimension(95, 25));
        resume.setSize(10, 60);
        resume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumeActionPerformed(evt);
            }
        });
        dialogpause.getContentPane().add(resume);
        resume.setBounds(135, 138, 129, 30);

        mainmenu.setSize(10, 60);
        mainmenu.setBackground(new java.awt.Color(255, 255, 255));
        mainmenu.setFont(new java.awt.Font("Lithos Pro Regular", 1, 20)); // NOI18N
        mainmenu.setText("MAIN MENU");
        mainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenuActionPerformed(evt);
            }
        });
        dialogpause.getContentPane().add(mainmenu);
        mainmenu.setBounds(110, 180, 180, 29);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/at53.jpg"))); // NOI18N
        dialogpause.getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 300);

        dialogkonfirmasi.setUndecorated(true);
        dialogkonfirmasi.getContentPane().setLayout(null);

        setujubutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/sip okei.png"))); // NOI18N
        setujubutton.setBorder(null);
        setujubutton.setBorderPainted(false);
        setujubutton.setContentAreaFilled(false);
        setujubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setujubuttonActionPerformed(evt);
            }
        });
        dialogkonfirmasi.getContentPane().add(setujubutton);
        setujubutton.setBounds(70, 160, 50, 50);

        tidaksetujubutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/exit hehe_1.png"))); // NOI18N
        tidaksetujubutton.setBorder(null);
        tidaksetujubutton.setBorderPainted(false);
        tidaksetujubutton.setContentAreaFilled(false);
        tidaksetujubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidaksetujubuttonActionPerformed(evt);
            }
        });
        dialogkonfirmasi.getContentPane().add(tidaksetujubutton);
        tidaksetujubutton.setBounds(280, 160, 50, 51);

        konfirmasi.setFont(new java.awt.Font("Lithos Pro Regular", 1, 48)); // NOI18N
        konfirmasi.setForeground(new java.awt.Color(255, 255, 255));
        konfirmasi.setText("ANDA YAKIN?");
        dialogkonfirmasi.getContentPane().add(konfirmasi);
        konfirmasi.setBounds(20, 90, 390, 49);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/at53.jpg"))); // NOI18N
        dialogkonfirmasi.getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 420, 300);

        jbenar.setUndecorated(true);

        labelbenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/benar (1).png"))); // NOI18N

        javax.swing.GroupLayout jbenarLayout = new javax.swing.GroupLayout(jbenar.getContentPane());
        jbenar.getContentPane().setLayout(jbenarLayout);
        jbenarLayout.setHorizontalGroup(
            jbenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbenarLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(labelbenar)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jbenarLayout.setVerticalGroup(
            jbenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jbenarLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(labelbenar)
                .addGap(91, 91, 91))
        );

        jsalah.setUndecorated(true);

        labelsalah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/salah (1).png"))); // NOI18N

        javax.swing.GroupLayout jsalahLayout = new javax.swing.GroupLayout(jsalah.getContentPane());
        jsalah.getContentPane().setLayout(jsalahLayout);
        jsalahLayout.setHorizontalGroup(
            jsalahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jsalahLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(labelsalah)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jsalahLayout.setVerticalGroup(
            jsalahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jsalahLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelsalah)
                .addGap(91, 91, 91))
        );

        gameover.setLocationByPlatform(true);
        gameover.setUndecorated(true);
        gameover.getContentPane().setLayout(null);

        setujubutton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/sip okei_1.png"))); // NOI18N
        setujubutton1.setBorder(null);
        setujubutton1.setBorderPainted(false);
        setujubutton1.setContentAreaFilled(false);
        setujubutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setujubutton1ActionPerformed(evt);
            }
        });
        gameover.getContentPane().add(setujubutton1);
        setujubutton1.setBounds(67, 201, 51, 53);

        tidaksetujubutton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/exit hehe.png"))); // NOI18N
        tidaksetujubutton1.setBorder(null);
        tidaksetujubutton1.setBorderPainted(false);
        tidaksetujubutton1.setContentAreaFilled(false);
        tidaksetujubutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidaksetujubutton1ActionPerformed(evt);
            }
        });
        gameover.getContentPane().add(tidaksetujubutton1);
        tidaksetujubutton1.setBounds(303, 201, 49, 51);

        jLabel1.setFont(new java.awt.Font("Lithos Pro Regular", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("KALAH!!!");
        gameover.getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 50, 240, 49);

        jLabel3.setFont(new java.awt.Font("Lithos Pro Regular", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MAIN LAGI?");
        gameover.getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 110, 340, 49);

        namascore.setFont(new java.awt.Font("Lithos Pro Regular", 1, 14)); // NOI18N
        namascore.setForeground(new java.awt.Color(255, 255, 255));
        gameover.getContentPane().add(namascore);
        namascore.setBounds(20, 160, 390, 27);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/at53.jpg"))); // NOI18N
        gameover.getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 430, 300);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setLayout(null);

        soal.setEditable(false);
        soal.setBackground(new java.awt.Color(253, 230, 120));
        soal.setColumns(20);
        soal.setFont(new java.awt.Font("Lithos Pro Regular", 1, 18)); // NOI18N
        soal.setLineWrap(true);
        soal.setRows(5);
        soal.setTabSize(2);
        soal.setText("Pernyataan");
        soal.setWrapStyleWord(true);
        soal.setAutoscrolls(false);
        soal.setFocusable(false);
        soal.setOpaque(false);
        panelSoal.setViewportView(soal);

        panel.add(panelSoal);
        panelSoal.setBounds(40, 60, 360, 160);

        score.setFont(new java.awt.Font("Lithos Pro Regular", 1, 20)); // NOI18N
        score.setForeground(new java.awt.Color(255, 255, 255));
        score.setText("0");
        panel.add(score);
        score.setBounds(40, 10, 52, 20);

        pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pause hehe.png"))); // NOI18N
        pause.setBorder(null);
        pause.setBorderPainted(false);
        pause.setContentAreaFilled(false);
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });
        panel.add(pause);
        pause.setBounds(390, 540, 50, 50);

        garis3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout garis3Layout = new javax.swing.GroupLayout(garis3);
        garis3.setLayout(garis3Layout);
        garis3Layout.setHorizontalGroup(
            garis3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        garis3Layout.setVerticalGroup(
            garis3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        panel.add(garis3);
        garis3.setBounds(210, 0, 10, 600);

        buttonbenar.setBorder(null);
        buttonbenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/benar (1).png"))); // NOI18N
        buttonbenar.setBorder(null);
        buttonbenar.setBorderPainted(false);
        buttonbenar.setContentAreaFilled(false);
        buttonbenar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonbenar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/benar (1).png"))); // NOI18N
        buttonbenar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/benar (1).png"))); // NOI18N
        buttonbenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbenarActionPerformed(evt);
            }
        });
        panel.add(buttonbenar);
        buttonbenar.setBounds(110, 490, 80, 80);

        salahbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/salah (1).png"))); // NOI18N
        salahbutton.setBorder(null);
        salahbutton.setBorderPainted(false);
        salahbutton.setContentAreaFilled(false);
        salahbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salahbuttonActionPerformed(evt);
            }
        });
        panel.add(salahbutton);
        salahbutton.setBounds(240, 490, 80, 80);

        waktu.setFont(new java.awt.Font("Lithos Pro Regular", 1, 20)); // NOI18N
        waktu.setForeground(new java.awt.Color(255, 255, 255));
        waktu.setText("0");
        panel.add(waktu);
        waktu.setBounds(370, 10, 26, 20);
        panel.add(char2);
        char2.setBounds(220, 310, 200, 190);
        panel.add(char1);
        char1.setBounds(20, 310, 200, 200);

        Background.setBackground(new java.awt.Color(0, 0, 0));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/2.JPG"))); // NOI18N
        panel.add(Background);
        Background.setBounds(0, 0, 450, 600);

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
        // TODO add your handling code here:
        loop=0;
        dialogpause.setVisible(true);
        dialogpause.setSize(400, 300);
        dialogpause.setLocationRelativeTo(this);
    }//GEN-LAST:event_pauseActionPerformed

    private void buttonbenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonbenarActionPerformed
        // TODO add your handling code here:
        gui_chara c = new gui_chara();
        if(c.karakter==1){
            char1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1.gif")));
            char1.setVisible(true);
            char2.setVisible(false);
        }else{
            char1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/2.gif")));
            char1.setVisible(true);
            char2.setVisible(false);
        }
        SystemGame x = new SystemGame(true, gui_chara.username);
        SystemGame.bs = false;
        x.setAnswer(true);
        jawab = 1;
    }//GEN-LAST:event_buttonbenarActionPerformed

    private void salahbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salahbuttonActionPerformed
        // TODO add your handling code here:
        gui_chara c = new gui_chara();
        if(c.karakter==1){
            char2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1.gif")));
            char2.setVisible(true);
            char1.setVisible(false);
        }else{
            char2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/2.gif")));
            char2.setVisible(true);
            char1.setVisible(false);
        }
        SystemGame x = new SystemGame(true, gui_chara.username);
        SystemGame.bs = false;
        x.setAnswer(false);
        jawab = 1;
    }//GEN-LAST:event_salahbuttonActionPerformed

    private void resumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumeActionPerformed
        // TODO add your handling code here:
        dialogpause.setVisible(false);
        loop=1;
        Thread xxx= new Thread(gimsistem);
        xxx.start();
    }//GEN-LAST:event_resumeActionPerformed

    private void mainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenuActionPerformed
        // TODO add your handling code here:       
        dialogpause.setVisible(false);
        dialogkonfirmasi.setVisible(true);
        dialogkonfirmasi.setSize(400, 300);
        dialogkonfirmasi.setLocationRelativeTo(this);
    }//GEN-LAST:event_mainmenuActionPerformed

    private void setujubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setujubuttonActionPerformed
        // TODO add your handling code here:
        MenuUtama ulang = new MenuUtama();
        this.setVisible(false);
        ulang.setVisible(true);
    }//GEN-LAST:event_setujubuttonActionPerformed

    private void tidaksetujubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidaksetujubuttonActionPerformed
        // TODO add your handling code here:
        MenuUtama x = new MenuUtama();
        this.setVisible(false);
        x.setVisible(true);
    }//GEN-LAST:event_tidaksetujubuttonActionPerformed

    private void tidaksetujubutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidaksetujubutton1ActionPerformed
        // TODO add your handling code here:
        loop = 0;
        Thread xxx = new Thread(gimsistem);
        xxx.stop();
        MenuUtama x = new MenuUtama();
        this.setVisible(false);
        x.setVisible(true);
    }//GEN-LAST:event_tidaksetujubutton1ActionPerformed

    private void setujubutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setujubutton1ActionPerformed
        // TODO add your handling code here:
        gui_chara ulang = new gui_chara();
        this.setVisible(false);
        ulang.setVisible(true);
    }//GEN-LAST:event_setujubutton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InGameFrame().setVisible(true);
            }
        });
    }
    Runnable gimsistem = new Runnable() {
        @Override
        public void run() {
            SystemGame x = new SystemGame(true, "");
            try {
                while (loop == 1) {
                    Thread.sleep(1000);
                    if (detik % 5 == 0) {
                        soal.setText(x.getSoal());
                    }
                    if (detik >= 0) {
                        waktu.setText(Integer.toString(detik));
                    }
                    if (jawab == 1) {
                        x.setScore();
                    }
                    if (SystemGame.bs == true) {
                        jawab = 0;
                        loop = 0;
                        jawabanBenar();
                        SystemGame.bs = false;
                        Thread.sleep(3000);
                        jbenar.setVisible(false);
                        score.setText(Integer.toString(x.getScore()));
                    }
                    if (SystemGame.bs == false && jawab == 1 || detik==0) {
                        jsalah.setSize(400, 300);
                        jsalah.setLocationRelativeTo(rootPane);
                        jsalah.setVisible(true);
                        Thread.sleep(3000);
                        jsalah.setVisible(false);
                        jawabanSalah();
                        break;
                    }
                    detik--;
                }

            } catch (Exception e) {
            }
        }
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton buttonbenar;
    private javax.swing.JLabel char1;
    private javax.swing.JLabel char2;
    private javax.swing.JDialog dialogkonfirmasi;
    private javax.swing.JDialog dialogpause;
    private javax.swing.JDialog gameover;
    private javax.swing.JPanel garis3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JDialog jbenar;
    private javax.swing.JDialog jsalah;
    private javax.swing.JLabel konfirmasi;
    private javax.swing.JLabel labelbenar;
    private javax.swing.JLabel labelsalah;
    private javax.swing.JButton mainmenu;
    private javax.swing.JLabel namascore;
    private javax.swing.JPanel panel;
    private javax.swing.JScrollPane panelSoal;
    private javax.swing.JButton pause;
    private javax.swing.JLabel pauselabel;
    private javax.swing.JButton resume;
    private javax.swing.JButton salahbutton;
    private javax.swing.JLabel score;
    private javax.swing.JButton setujubutton;
    private javax.swing.JButton setujubutton1;
    private javax.swing.JTextArea soal;
    private javax.swing.JButton tidaksetujubutton;
    private javax.swing.JButton tidaksetujubutton1;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables

    @Override
    public void jawabanBenar() {
        loop = 1;
        detik = 6;
        jbenar.setSize(400, 300);
        jbenar.setLocationRelativeTo(this);
        jbenar.setVisible(true);
    }
// BARU
    @Override
    public void jawabanSalah() {
        SystemGame x = new SystemGame(true, "");
        try {
                String sql = "Select * from player ORDER BY id_player ASC";
                java.sql.Connection conn = (Connection) Config.configDB();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);
                while (res.next()) {
                    id = Integer.parseInt(res.getString("id_player"));
                }
            } catch (Exception e) {
            }
        try {
            String sql = "Select * from player where id_player='" + id + "'";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                info = "Nama : "+res.getString(2)+" Score : "+Integer.parseInt(res.getString("score"));
            }
        } catch (Exception e) {
        }
        namascore.setText(info);
        loop=0;
        gameover.setVisible(true);
        gameover.setSize(400, 300);
        gameover.setLocationRelativeTo(this);
    }
}
