package game;

import java.sql.Connection;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author BOOL&QUIZ
 */
public class Score extends javax.swing.JFrame {

    /**
     * Creates new form Score
     */
    public Score() {
        initComponents();
        LoadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clickreset = new javax.swing.JDialog();
        aysreset = new javax.swing.JLabel();
        okereset = new javax.swing.JButton();
        batalreset = new javax.swing.JButton();
        resetbg = new javax.swing.JLabel();
        scorepanel = new javax.swing.JPanel();
        hs = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelskor = new javax.swing.JTable();
        scorebg = new javax.swing.JLabel();

        clickreset.setResizable(false);
        clickreset.getContentPane().setLayout(null);

        aysreset.setFont(new java.awt.Font("Lithos Pro Regular", 1, 36)); // NOI18N
        aysreset.setForeground(new java.awt.Color(255, 255, 255));
        aysreset.setText("ANDA YAKIN?");
        clickreset.getContentPane().add(aysreset);
        aysreset.setBounds(60, 90, 290, 50);

        okereset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/sip okei.png"))); // NOI18N
        okereset.setBorder(null);
        okereset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okeresetActionPerformed(evt);
            }
        });
        clickreset.getContentPane().add(okereset);
        okereset.setBounds(50, 210, 47, 50);

        batalreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/exit hehe.png"))); // NOI18N
        batalreset.setBorder(null);
        batalreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalresetActionPerformed(evt);
            }
        });
        clickreset.getContentPane().add(batalreset);
        batalreset.setBounds(270, 210, 47, 50);

        resetbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/at53.jpg"))); // NOI18N
        clickreset.getContentPane().add(resetbg);
        resetbg.setBounds(0, 0, 400, 300);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scorepanel.setLayout(null);

        hs.setFont(new java.awt.Font("Lithos Pro Regular", 1, 36)); // NOI18N
        hs.setText("SKOR TERTINGGI");
        scorepanel.add(hs);
        hs.setBounds(50, 60, 340, 50);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/back hehe.png"))); // NOI18N
        back.setBorder(null);
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        scorepanel.add(back);
        back.setBounds(20, 530, 49, 50);

        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/replay hehe.png"))); // NOI18N
        reset.setBorder(null);
        reset.setBorderPainted(false);
        reset.setContentAreaFilled(false);
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        scorepanel.add(reset);
        reset.setBounds(380, 530, 49, 50);

        tabelskor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane2.setViewportView(tabelskor);

        scorepanel.add(jScrollPane2);
        jScrollPane2.setBounds(30, 220, 390, 120);

        scorebg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        scorebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/at52.jpg"))); // NOI18N
        scorepanel.add(scorebg);
        scorebg.setBounds(0, 0, 450, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scorepanel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scorepanel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        MenuUtama menu = new MenuUtama();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        clickreset.setSize(400, 300);
        clickreset.setLocationRelativeTo(this);
        clickreset.setVisible(true);
    }//GEN-LAST:event_resetActionPerformed

    private void okeresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okeresetActionPerformed
        // TODO add your handling code here:
        try {
            //'05:12:11'
            String sql = "DELETE FROM player";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
        } catch (Exception e) {
        }
        LoadTable();
        clickreset.setVisible(false);
    }//GEN-LAST:event_okeresetActionPerformed

    private void batalresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalresetActionPerformed
        // TODO add your handling code here:
        clickreset.setVisible(false);
    }//GEN-LAST:event_batalresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Score().setVisible(true);
            }
        });
    }

    private void LoadTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Nama");
        model.addColumn("Skor");

        //menampilkan data database kedalam tabel
        try {
            int no = 1;
            String sql = "select * from player ORDER BY score DESC LIMIT 5";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{no++, res.getString(2), res.getString("score")});
            }
            tabelskor.setModel(model);
        } catch (Exception e) {
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aysreset;
    private javax.swing.JButton back;
    private javax.swing.JButton batalreset;
    private javax.swing.JDialog clickreset;
    private javax.swing.JLabel hs;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton okereset;
    private javax.swing.JButton reset;
    private javax.swing.JLabel resetbg;
    private javax.swing.JLabel scorebg;
    private javax.swing.JPanel scorepanel;
    private javax.swing.JTable tabelskor;
    // End of variables declaration//GEN-END:variables
}
